engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      quote-props:
        enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**/*

exclude_paths:
- docs
- test
- "**/vendor/**/*"
